### ISSUE TITLE
Issue a stable release?

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#5]
Can you issue a stable release version of OSG-GEM?

**Comment by feltus** [comment]
Hey Will.  Do we have a stable release?  Have there been changes to the
master fork?  Maybe we should be working on a branch?  Ask Mats and this
may be urgent since stephen is using for a class.

**Comment by wpoehlm** [comment]
Hey Stephen,

We can use an older version that uses the Pegasus 4.6.2 module, but this version will only let you run one dataset per workflow, and the fastq files have to be on an OSG filesystem.  The most recent commit has been tested for a few weeks and it was working for me yesterday, so let's try to figure out exactly what is going on. There was network downtime last week and submit hosts were down a few days ago, which could have affected your workflow if it was submitted before then.  

Can you point me to your workflow directory?  I think I can access it since we're in the same project group.  Are you running the test files that are cloned with the workflow, or is this a large experiment?  

Thanks

Will
